template = "https://github.com/giellalt/template-lang-und"
rev_id = 267
template_sha = "eecc8ba78a1297394fa54b425d94002ee6604eb1"

[replacements]
__GLOTTOLOG_ID__ = "thai1261"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-tha"
__UND2C__ = "th"
__UNDEFINED__ = "Thai"
__UND__ = "tha"
