template = ""
rev_id = 165
template_sha = "e90d50ced16049c0fd339de88458c3e44708f347"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-tha"
__UND2C__ = "th"
__UNDEFINED__ = "Thai"
__UND__ = "tha"
