template = ""
rev_id = 169
template_sha = "e276366f8280e53d907be9b90035b3e59502b1d8"

[replacements]
__LICENCE__ = "GPLv3"
__REPO__ = "lang-tha"
__UND2C__ = "th"
__UNDEFINED__ = "Thai"
__UND__ = "tha"
