template = "https://github.com/giellalt/template-lang-und"
rev_id = 271
template_sha = "58889500fa56906fc67098b753f74968988220af"

[replacements]
__GLOTTOLOG_ID__ = "thai1261"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-tha"
__UND2C__ = "th"
__UNDEFINED__ = "Thai"
__UND__ = "tha"
